cache:
  directories:
  - $HOME/.m2
  - $HOME/.jdk
sudo: false
env:
  global:
  - JDKW=https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh
  - JDKW_VERSION=8u65
  - JDKW_BUILD=b17
install: true
#before_script:
#- gpg --import arpnetworking.key
script:
- curl -s ${JDKW} | bash /dev/stdin ./mvnw clean install --settings settings.xml -P ci -Dgpg.skip=true -U
- if [ \( -n "${TRAVIS_TAG}" \) -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then curl -s ${JDKW} | bash /dev/stdin ./mvnw deploy --settings settings.xml -P ci -DskipAllVerification=true; fi;
