language: java
sudo: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: true
#before_script:
#- gpg --import arpnetworking.key
script:
- ./mvnw clean install --settings settings.xml -P ci -Dgpg.skip=true -U
- if [ \( -n "${TRAVIS_TAG}" \) -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./mvnw deploy --settings settings.xml -P ci -DskipAllVerification=true; fi;
